---
title: ""
runtime: shiny
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<center> 
# *About* 


This is a web application created in R Shiny with the support of R Markdown documents. If you are unfamiliar with the tools used in this app and would like to learn more, links to some helpful resources will be listed in the Further Reading section. 

The purpose of this app is very simple; take a user's text that they input and generate next word predictions based on what was typed. This concept is very similar to how smart phones and search engines provide auto-complete results whenever you send a text message or look up information on Google. However, it is obviously much less sophisticated as it only looks one word into the future as opposed to Google's longer (and usually more relevant) search strings. Nonetheless, the functionality of the app provides basic some insight as to how predictive text algorithms are implemented and how incredibly useful they can be. 

We already see this in action on websites like Google and YouTube, in messenger apps, and email. [Google](https://www.google.com/search/howsearchworks/algorithms/) provides several related search results whenever you type anything in the search bar instantaneously, all by just looking at the words of your query. [YouTube](https://www.youtube.com/watch?v=gTrLniP5tSQ&ab_channel=YouTubeCreators), one of the world's most popular video hosting websites, creates tailor-made experiences based on search and watch history. Text messaging apps have been using autocompletion for years, and more recently Gmail has rolled out [Smart Compose](https://www.blog.google/products/gmail/subject-write-emails-faster-smart-compose-gmail/) to help users write emails faster than ever before.         
</center>

