---
title: ""
runtime: shiny
output: html_document
---

# *Some final thoughts*

While I feel satisfied about the implementation of the model itself, there are definitely some significant improvements that could have been made in the data cleaning process. Cases where sentences were created from the corpus where names of people containing proper titles like "Mr." or "Mrs." were problematic. Handling punctuation was also a challenge given the nature of some of the corpora, especially Tweets. As a result many n-grams were generated that were unintended or simply not a part of the original corpus. Overall the data preparation stage could be improved greatly. 

The original sample corpus used to train the model contained 50% of the text from each of the blog, news, and Twitter files. The performance of a back-off model and language models in general is greatly tied to the size of the corpus it was trained on. A bigger corpus means being able to capture a wide variety of words with more certainty in their probabilities of appearing in a random context. Increasing the size of the training corpus, including a wider variety of literature outside of the categories provided, and expanding the test corpus are all potential improvements to consider. 

### *Helpful Resources*

* [A good starting point for learning about KBO](https://en.wikipedia.org/wiki/Katz%27s_back-off_model)
* [An incredibly helpful guide on understanding KBO in action](https://thachtranerc.wordpress.com/2016/04/12/katzs-backoff-model-implementation-in-r/)
* [An overview on smoothing which includes Good-Turing](https://www.cs.cornell.edu/courses/cs4740/2014sp/lectures/smoothing+backoff.pdf)
* [Good-Turing discounting](http://www.seas.ucla.edu/spapl/weichu/htkbook/node214_mn.html)
* [shinydashboard package used to create the UI of this app](https://rstudio.github.io/shinydashboard/index.html)
* [R Markdown, a very handy tool for creating documents combining text and code](https://rstudio.github.io/shinydashboard/index.html)
* [Guide to the data.table package](https://cran.r-project.org/web/packages/data.table/vignettes/datatable-intro.html)
* [Guide to the quanteda package](https://quanteda.io/articles/quickstart.html)
